import { useQuery, useMutation } from '@tanstack/react-query'
import { Dialog, DialogContent } from '@/components/ui/dialog'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import { Button } from '@/components/ui/button'
import { Badge, type BadgeProps } from '@/components/ui/badge'
import { Inset } from '@/components/ui/card'
import { LoadingRow } from '@/components/ui/spinner'
import { ugx } from '@/lib/utils'

/** Projects the backend can build an audit for. */
export const AUDITABLE = new Set([
  'washing_bay', 'trees', 'sheep', 'dairy', 'irrigation',
  'bees', 'chicken', 'mango', 'goats', 'rabbits', 'fish',
])

interface Assumption {
  variable: string
  type: string
  confidence: string
  value: string | number
  unit?: string
  source: string
  evidence: string
}
interface Formula {
  metric: string; formula: string; substitution: string; result: string; note?: string
}
interface WhatIf { scenario: string; impact: string }
interface AuditData {
  project: string
  status: string
  assumptions: Assumption[]
  formula_derivations: Formula[]
  data_gaps: string[]
  what_would_change: WhatIf[]
}
interface Narrative {
  narrative: string
  provider: string
  based_on?: { assumptions_count: number; formulas_count: number; data_gaps_count: number }
}

const TYPE_TONE: Record<string, BadgeProps['tone']> = {
  ACTUAL: 'success', ESTIMATE: 'info', PROJECTION: 'purple', ASSUMPTION: 'warning', UNKNOWN: 'danger',
}
const CONF_TONE: Record<string, BadgeProps['tone']> = {
  HIGH: 'success', MEDIUM: 'warning', LOW: 'danger',
}

function assumptionValue(a: Assumption): string {
  if (a.unit && typeof a.value === 'number') {
    return a.unit.includes('UGX') ? ugx(a.value) : `${a.value.toLocaleString()} ${a.unit}`
  }
  return a.unit ? `${a.value} ${a.unit}` : String(a.value)
}

const NARRATIVE_SECTIONS = [
  { key: 'EXECUTIVE SUMMARY', color: '#60a5fa', icon: '📋' },
  { key: 'KEY STRENGTHS', color: '#22c55e', icon: '✅' },
  { key: 'KEY RISKS', color: '#ef4444', icon: '⚠️' },
  { key: 'WHAT THE FAMILY SHOULD DO NEXT', color: '#f59e0b', icon: '🎯' },
  { key: 'BOARD RECOMMENDATION', color: '#a78bfa', icon: '⚖️' },
  { key: 'SURPRISING INSIGHT', color: '#fcd34d', icon: '💡' },
]

function parseNarrative(text: string): { key: string; body: string }[] {
  const out: Record<string, string> = {}
  let current = ''
  for (const line of text.split('\n')) {
    const matched = NARRATIVE_SECTIONS.find(s => line.toUpperCase().includes(s.key))
    if (matched) { current = matched.key; out[current] = ''; continue }
    if (current) out[current] += line + '\n'
  }
  return NARRATIVE_SECTIONS.filter(s => out[s.key]?.trim()).map(s => ({ key: s.key, body: out[s.key].trim() }))
}

function AiBrief({ projectId }: { projectId: string }) {
  const narrative = useMutation<Narrative>({
    mutationFn: () =>
      fetch(`/api/projects/${projectId}/narrative`, { method: 'POST', credentials: 'include' }).then(r => r.json()),
  })

  if (narrative.isPending) {
    return <LoadingRow label="Analysing the project, this can take up to a minute…" />
  }

  if (!narrative.data) {
    return (
      <div className="px-2 py-8 text-center">
        <div className="mb-3 text-4xl">🤖</div>
        <div className="mb-1 text-sm font-semibold text-[var(--foreground)]">AI Board Analysis</div>
        <p className="mx-auto mb-4 max-w-sm text-xs text-[var(--muted-2)]">
          The AI reads every assumption, formula, and data gap, then writes a board quality investment brief.
        </p>
        <Button onClick={() => narrative.mutate()}>⚡ Generate Analysis</Button>
      </div>
    )
  }

  const sections = parseNarrative(narrative.data.narrative || '')
  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <span className="text-[11px] text-[var(--muted-2)]">Generated by {narrative.data.provider || 'AI'}</span>
        {narrative.data.based_on && (
          <Badge tone="neutral">{narrative.data.based_on.assumptions_count} assumptions analysed</Badge>
        )}
        <Button variant="ghost" size="sm" className="ml-auto" onClick={() => narrative.mutate()}>🔄 Refresh</Button>
      </div>
      {sections.map(s => {
        const meta = NARRATIVE_SECTIONS.find(m => m.key === s.key)!
        return (
          <div key={s.key} className="mb-3">
            <div className="mb-1.5 flex items-center gap-2 text-xs font-bold" style={{ color: meta.color }}>
              <span>{meta.icon}</span>{s.key}
            </div>
            <p className="whitespace-pre-line text-[13px] leading-relaxed text-[#cbd5e1]">{s.body}</p>
          </div>
        )
      })}
    </div>
  )
}

export function AuditModal({
  projectId, projectName, icon, open, onOpenChange,
}: {
  projectId: string; projectName: string; icon: string; open: boolean; onOpenChange: (o: boolean) => void
}) {
  const { data, isLoading } = useQuery<AuditData>({
    queryKey: ['audit', projectId],
    queryFn: () => fetch(`/api/projects/${projectId}/audit`, { credentials: 'include' }).then(r => r.json()),
    enabled: open,
    staleTime: 300_000,
  })

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent title={`${icon} ${projectName}`} subtitle="Audit Report · Assumptions · AI Analysis">
        {isLoading || !data ? (
          <LoadingRow label="Loading audit data…" />
        ) : (
          <Tabs defaultValue="assumptions">
            <TabsList>
              <TabsTrigger value="assumptions">📋 Assumptions</TabsTrigger>
              <TabsTrigger value="formulas">🧮 Formulas</TabsTrigger>
              <TabsTrigger value="gaps">⚠️ Gaps</TabsTrigger>
              <TabsTrigger value="ai">🤖 AI Brief</TabsTrigger>
            </TabsList>

            <TabsContent value="assumptions">
              <p className="mb-3 text-[11px] text-[var(--muted-2)]">
                Every number is built on the inputs below. Type = where it comes from. Confidence = how reliable it is.
              </p>
              {data.assumptions.map((a, i) => (
                <Inset key={i} className="mb-2.5 p-3.5">
                  <div className="mb-2 flex items-start justify-between gap-2">
                    <div className="flex-1 text-sm font-bold text-[var(--foreground)]">{a.variable}</div>
                    <div className="flex shrink-0 gap-1">
                      <Badge tone={TYPE_TONE[a.type] ?? 'neutral'}>{a.type}</Badge>
                      <Badge tone={CONF_TONE[a.confidence] ?? 'neutral'}>{a.confidence}</Badge>
                    </div>
                  </div>
                  <div className="mb-1.5 text-base font-bold text-[#60a5fa]">{assumptionValue(a)}</div>
                  <div className="text-[11px] text-[var(--muted-2)]">Source: <span className="text-[var(--muted)]">{a.source}</span></div>
                  <div className="text-[11px] text-[var(--muted-2)]">Evidence: <span className="text-[var(--muted)]">{a.evidence}</span></div>
                </Inset>
              ))}
            </TabsContent>

            <TabsContent value="formulas">
              <p className="mb-3 text-[11px] text-[var(--muted-2)]">
                Every computed metric, with the formula and the actual values substituted in.
              </p>
              {data.formula_derivations.map((f, i) => (
                <Inset key={i} className="mb-2.5 p-3.5">
                  <div className="mb-2 text-sm font-bold text-[var(--foreground)]">{f.metric}</div>
                  <div className="rounded-lg bg-[var(--background)] p-2.5 font-mono">
                    <div className="text-[10px] text-[var(--muted-2)]">FORMULA</div>
                    <div className="text-[13px] text-[#a78bfa]">{f.formula}</div>
                    <div className="mt-2 text-[10px] text-[var(--muted-2)]">WITH VALUES</div>
                    <div className="text-[13px] text-[#60a5fa]">{f.substitution}</div>
                    <div className="mt-2 text-[10px] text-[var(--muted-2)]">RESULT</div>
                    <div className="text-base font-bold text-[var(--foreground)]">{f.result}</div>
                  </div>
                  {f.note && <div className="mt-2 border-l-2 border-[var(--border)] pl-2 text-[11px] text-[var(--muted)]">Note: {f.note}</div>}
                </Inset>
              ))}
              {data.what_would_change.length > 0 && (
                <>
                  <div className="my-3 text-xs font-bold text-[var(--muted)]">SENSITIVITY: WHAT IF KEY ASSUMPTIONS CHANGE?</div>
                  {data.what_would_change.map((w, i) => (
                    <Inset key={i} className="mb-1.5 p-2.5">
                      <div className="text-[11px] font-bold text-[#f59e0b]">IF: {w.scenario}</div>
                      <div className="mt-1 text-xs text-[var(--muted)]">THEN: {w.impact}</div>
                    </Inset>
                  ))}
                </>
              )}
            </TabsContent>

            <TabsContent value="gaps">
              <div className="mb-4 rounded-lg border border-[#991b1b] bg-[var(--danger-soft)]/30 p-3.5">
                <div className="mb-1 text-xs font-bold text-[#fca5a5]">⚠️ DATA GAPS — {data.data_gaps.length} issues found</div>
                <div className="text-xs text-[#fca5a5]">These gaps reduce confidence in the projections. Address them to make the numbers more reliable.</div>
              </div>
              {data.data_gaps.map((g, i) => {
                const critical = g.toUpperCase().includes('CRITICAL')
                return (
                  <Inset key={i} className="mb-2 p-3" style={{ borderLeft: `3px solid ${critical ? '#ef4444' : '#f59e0b'}` }}>
                    <div className="flex items-start gap-2">
                      <Badge tone={critical ? 'danger' : 'warning'}>{critical ? 'CRITICAL' : `GAP ${i + 1}`}</Badge>
                      <div className="text-[13px] text-[var(--foreground)]">{g}</div>
                    </div>
                  </Inset>
                )
              })}
            </TabsContent>

            <TabsContent value="ai">
              <AiBrief projectId={projectId} />
            </TabsContent>
          </Tabs>
        )}
      </DialogContent>
    </Dialog>
  )
}
